[package]
name = "webgpu-sandbox-web"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.89"
wasm-bindgen-futures = "0.4.39"
js-sys = "0.3.66"
nalgebra-glm = "0.18.0"
gltf = "1.4.0"

[dependencies.web-sys]
version = "0.3.66"
features = ["Document", "Element", "HtmlElement", "Node", "Window", "Navigator", "WorkerGlobalScope", "WorkerNavigator", "Gpu", "GpuAdapter", "GpuDevice", "GpuSupportedFeatures", "GpuCanvasContext", "GpuCanvasConfiguration", "GpuTextureFormat", "GpuShaderModule", "GpuShaderModuleDescriptor", "GpuRenderPipeline", "GpuRenderPipelineDescriptor", "GpuCanvasAlphaMode", "GpuVertexState", "GpuFragmentState", "GpuPipelineLayout", "GpuPipelineLayoutDescriptor", "GpuBindGroup", "GpuColorTargetState", "GpuPrimitiveState", "GpuPrimitiveTopology", "GpuCommandEncoder", "GpuTexture", "GpuTextureView", "GpuTextureDescriptor", "GpuRenderPassDescriptor", "GpuRenderPassColorAttachment", "GpuRenderPassEncoder", "GpuLoadOp", "GpuStoreOp", "GpuColorDict", "GpuQueue", "GpuCommandBuffer", "GpuMultisampleState", "gpu_texture_usage", "GpuBuffer", "GpuBufferDescriptor", "gpu_buffer_usage", "GpuVertexBufferLayout", "GpuVertexAttribute", "GpuVertexFormat", "GpuBindGroupDescriptor", "GpuBindGroupLayout", "GpuBindGroupLayoutEntry", "GpuBindGroupEntry", "gpu_shader_stage", "GpuBufferBindingLayout", "GpuBufferBinding", "GpuBindGroupLayoutDescriptor", "GpuBufferBindingType", "GpuDepthStencilState", "GpuCompareFunction", "GpuIndexFormat", "GpuRenderPassDepthStencilAttachment", "HtmlCanvasElement", "Headers", "Request", "RequestInit", "RequestMode", "Response", "Blob", "console", "Location"]
